#!/usr/bin/env python3
"""Recursive split-and-solve driver for the (3,9;34) enumeration cubes.

Usage: enum34_driver.py <worker_id> <num_workers> <cube_file> <outdir>

Each top-level cube (1-based line in <cube_file>, round-robin over workers)
is solved with --all-graphs.  If it exceeds the timeout it is split deeper
(--simple-assignment-cutoff, --prerun) and the subcubes are solved
recursively (deeper level => bigger cutoff and timeout).  Subcube files are
generated by smsg itself (cubes blocked by clauses => exhaustive cover);
generation is never truncated — if a split explodes past MAX_SUBCUBES the
cube is retried with an intermediate cutoff, per CLAIMS.md pitfall note.

Ledger: <outdir>/done_<idx> holds "OK <n_solutions> <depth_used>" per
top-level cube.  Solutions (edge-list lines) go to <outdir>/sol_<idx>.out.
"""
import os
import subprocess
import sys

SMSG = os.path.expanduser("~/.local/bin/smsg")
BASE = ["--vertices", "34", "--dimacs", "/tmp/t34.cnf",
        "--forbidden-subgraph-file", "data/forb_k3.txt",
        "--forbidden-induced-subgraph-file", "data/forb_i9.txt"]
CUTOFFS = {1: 170, 2: 220, 3: 280, 4: 340}   # split cutoff at depth d
TIMEOUTS = {0: 120, 1: 120, 2: 180, 3: 300, 4: 10 ** 9}
MAX_SUBCUBES = 400000


def solve(cube_file, idx, depth, sols, outdir, tag):
    to = TIMEOUTS[depth]
    cmd = [SMSG, "--all-graphs", *BASE,
           "--cube-file", cube_file, "--cube-line", str(idx)]
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=to)
        out = p.stdout
        finished = "Number of graphs" in out or "Result" in out
    except subprocess.TimeoutExpired as ex:
        out = (ex.stdout or b"").decode() if isinstance(ex.stdout, bytes) \
            else (ex.stdout or "")
        finished = False
    if finished:
        got = [l for l in out.splitlines() if l.startswith("[(")]
        sols.extend(got)
        return depth
    # timeout: split deeper
    ndepth = depth + 1
    if ndepth not in CUTOFFS:
        raise RuntimeError(f"cube {tag}: exceeded max depth")
    cutoff = CUTOFFS[ndepth]
    while True:
        sub = os.path.join(outdir, f"sub_{tag}.icnf")
        gen = subprocess.run(
            [SMSG, *BASE, "--cube-file", cube_file, "--cube-line", str(idx),
             "--simple-assignment-cutoff", str(cutoff), "--prerun", "5"],
            capture_output=True, text=True)
        lines = [l for l in gen.stdout.splitlines() if l.startswith("a ")]
        # solutions can be found during prerun of splitting
        sols.extend(l for l in gen.stdout.splitlines() if l.startswith("[("))
        if len(lines) <= MAX_SUBCUBES:
            break
        cutoff = (CUTOFFS[depth] if depth in CUTOFFS else 120 + cutoff) \
            // 2 + cutoff // 2  # intermediate cutoff, retry
        cutoff -= 10
    if not lines:
        # split found no open subcubes => cube fully refuted during prerun
        return ndepth
    with open(sub, "w") as f:
        f.write("\n".join(lines) + "\n")
    maxd = ndepth
    for sidx in range(1, len(lines) + 1):
        maxd = max(maxd, solve(sub, sidx, ndepth, sols, outdir,
                               f"{tag}.{sidx}"))
    os.remove(sub)
    return maxd


def main():
    w, nw, cube_file, outdir = (int(sys.argv[1]), int(sys.argv[2]),
                                sys.argv[3], sys.argv[4])
    os.makedirs(outdir, exist_ok=True)
    ncubes = sum(1 for _ in open(cube_file))
    for idx in range(1, ncubes + 1):
        if (idx - 1) % nw != w:
            continue
        done = os.path.join(outdir, f"done_{idx}")
        if os.path.exists(done):
            continue
        sols = []
        maxd = solve(cube_file, idx, 0, sols, outdir, str(idx))
        with open(os.path.join(outdir, f"sol_{idx}.out"), "w") as f:
            f.write("\n".join(sols) + ("\n" if sols else ""))
        with open(done, "w") as f:
            f.write(f"OK {len(sols)} {maxd}\n")


if __name__ == "__main__":
    main()
